### ISSUE TITLE
Bootstrap Account Creation Page

### ISSUE THREAD

**Issue by ZYostSass** [ZYostSass/EPL-Card-Reader-Interface#15]
Create a landing page for bootstrap so that a user may create a new account. While waiting on login functionality focus on creating a button/link on the webpage somewhere for "create account" with buttons and input boxes, even if that information isn't saved or stored (yet!)

**Comment by DomovoiG** [comment]
page has been made. I don't have a full scope as to what info should be on this page. it seems really similar to the add_user_form info. Not sure if we should be repeating this work.
