### ISSUE TITLE
List of users that updates when scanning in

### ISSUE THREAD

**Issue by ZYostSass** [ZYostSass/EPL-Card-Reader-Interface#24]
We'll need a way to store all the users that scanned in for each day. Eventually they'll want a scan out, but unless you find a super simple and clean solution and have plenty of time I'm not worried about a scan out. (They don't even have a system to enforce scanning out to begin with, yet.)

**Comment by natashanaylor** [comment]
I created a template for this in my most recent PR. It's located in dashboard.html, currently with placeholder data. Feel free to add or take away any data in that log and design as you please.

**Comment by DomovoiG** [comment]
I've implemented some functions for the CSV file log. I'm going to add the functionality to the actual webpage after this pr.

**Comment by DomovoiG** [comment]
okay the list of users is implemented by Mikayla and the additional feature of having the card reader data saved on badge swipe is also completed. We can create a new ticket for any additional features. I'm going to leave the card reader data as a backend only system, not visible to the users.
