### ISSUE TITLE
Add User Button, Input 'Text' Box

### ISSUE THREAD

**Issue by ZYostSass** [ZYostSass/EPL-Card-Reader-Interface#33]
Look at examples we see/use in our daily lives for inputting data to a website, whether that's logging in or filling a survey or leaving a comment on a media website. We want something easily readable that Ed would use as a demo. 

Data points we'll need:

- PSUID#
- Badge#
- First Name
- Last Name
- pdx email

Bonus:

- Safety Waiver status (true/false to indicate if it's been signed.) This data point may be incorporated into the embedded google doc form in the future, so keep this in mind. This is why it's a bonus at this point.

Machines and admin privileges will be added in a future sprint.

**Comment by DomovoiG** [comment]
This looks like it's already been resolved by the dashboard page. It seems like we can just use what is already in place for adding users. I'll check in again but this should be closed.
