### ISSUE TITLE
Purge a database.

### ISSUE THREAD

**Issue by ZYostSass** [ZYostSass/EPL-Card-Reader-Interface#35]
Always a useful functionality. Research how we'd delete/purge/clean out an existing lab database for whatever reason with our framework of Flask, SQLAlchemy etc.

**Comment by mikayla-maki** [comment]
purge_database has been added to user options, time to make a button :D

**Comment by mikayla-maki** [comment]
The UI for this has been added in: https://github.com/ZYostSass/EPL-Card-Reader-Interface/pull/107
