### ISSUE TITLE
Local Deployment Ngrok

### ISSUE THREAD

**Issue by ZYostSass** [ZYostSass/EPL-Card-Reader-Interface#9]
Deployment and server options. https://ngrok.com/
Ngrok specializes in local deployment; not as secure, but sponsors shared this is not a concern (yet.)
See if you can take  the initial flask tutorial and “deploy it” using ngrok to give a demo. Alternatively if you have your own practice app, feel free to try deploying that instead.

**Comment by gleason9113** [comment]
Ngrok deployment process documented - super easy.
